name : Auto assign TA
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Get collaborators
      id: collaborators
      # use github api to get all collaborators of the repo
      run: |
        # exclude the logins
        exclude_logins=("github-actions[bot]" "lazovik" "feitosa-daniel" "andrewlalis" "Heerkog" "reinsmedinga" "Erblin-Ibrahimi" "Stylo2k" "BugelNiels" "taars-bot")
        # get all collaborators
        collaborators=$(curl -H "Authorization: Bearer ${{secrets.OWNER_TOKEN}}" -s "https://api.github.com/repos/${{ github.repository }}/collaborators?per_page=100" | jq -r '.[].login')
        
        echo "UnFiltered collaborators: ${collaborators[@]}"

        filtered_collaborators=()

        # filter out the excluded logins
        for collaborator in ${collaborators[@]}; do
            if [[ ! " ${exclude_logins[@]} " =~ " ${collaborator} " ]]; then
                filtered_collaborators+=($collaborator)
            fi
        done
        
        # print the collaborators
        echo "Found collaborators: ${filtered_collaborators[@]}"

        # assign the collaborators to the output
        {
          echo 'collaborators<<EOF'
          echo ${filtered_collaborators[@]}
          echo EOF
        } >> $GITHUB_OUTPUT
    - name: Assign TA
      uses: pozil/auto-assign-issue@v1.12.0
      with:
        assignees: ${{ steps.collaborators.outputs.collaborators }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        numOfAssignee: 3
